import { AdvancedSettingsParams } from '../components/organisms/common/advanced-parameters';

export const advancedControlSettings: AdvancedSettingsParams[] = [
  {
    label: 'Seed',
    type: 'input',
    controlName: 'seed',
    defaultValue: '',
  },
  {
    label: 'Stop Sequence',
    type: 'input',
    controlName: 'stopSequence',
    defaultValue: '',
  },
  {
    label: 'Temperature',
    type: 'slider',
    controlName: 'temperature',
    defaultValue: '',
  },
  {
    label: 'Mirostat',
    type: 'slider',
    controlName: 'mirostat',
    defaultValue: '',
  },
  {
    label: 'Mirostat Eta',
    controlName: 'mirostatEta',
    type: 'slider',
    defaultValue: '',
  },
  {
    label: 'Mirostat Tau',
    type: 'slider',
    controlName: 'mirostatTau',
    defaultValue: '',
    min: 0,
    max: 10,
  },
  {
    label: 'Top K',
    type: 'slider',
    controlName: 'topK',
    defaultValue: '',
    min: 0,
    max: 10,
  },
  {
    label: 'Top P',
    type: 'slider',
    controlName: 'topP',
    defaultValue: '',
    min: 0,
    max: 100,
  },
  {
    label: 'Min P',
    type: 'slider',
    controlName: 'minP',
    defaultValue: '',
  },
  {
    label: 'Frequency Penalty',
    type: 'slider',
    controlName: 'frequencyPenalty',
    defaultValue: '',
  },
  {
    label: 'Repeat Last N',
    type: 'slider',
    defaultValue: '',
    controlName: 'repeatLastN',
    min: -1.0,
    max: 128,
    step: 1,
  },
  {
    label: 'Tfs Z',
    type: 'slider',
    controlName: 'tfsZ',
    defaultValue: '',
    min: 0.0,
    max: 2.0,
  },
  {
    label: 'Context Length',
    type: 'slider',
    controlName: 'contextLength',
    defaultValue: '',
    min: 2048.0,
    max: 10240000.0,
    step: 1,
  },
  {
    label: 'Batch Size (num_batch)',
    type: 'slider',
    controlName: 'batchSize',
    defaultValue: '',
    min: 256,
    max: 8192,
    step: 1,
  },
  {
    label: 'Tokens To Keep on Context Refresh (num_keep)',
    type: 'slider',
    controlName: 'tokensToKeep',
    defaultValue: '',
    min: 24.0,
    max: 10240000,
    step: 1,
  },
  {
    label: 'Max Tokens (num_predict)',
    type: 'slider',
    controlName: 'maxTokens',
    defaultValue: '',
    min: -2,
    max: 16000,
    step: 1,
  },
  {
    label: 'Ollama: use_mmap',
    type: 'switch',
    controlName: 'ollamaUseMnap',
    defaultValue: '',
  },
  {
    label: 'Ollama: use_mlock',
    type: 'switch',
    controlName: 'ollamaUseMLock',
    defaultValue: '',
  },
  {
    label: 'Ollama: num_thread',
    type: 'slider',
    controlName: 'ollamaNumThreads',
    defaultValue: '',
    min: 1,
    max: 256,
    step: 1,
  },
  {
    label: 'Ollama: num_gpu',
    type: 'slider',
    controlName: 'ollamaNumGpus',
    defaultValue: '',
    min: 0,
    max: 256,
    step: 1,
  },
];
